services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gui
    environment:
      PMA_HOST: mariadb
      PMA_USER: admin
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
